# Generated by Django 5.2.4 on 2025-07-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='archivo_pdf',
            new_name='pdf',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='libro',
            name='clasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libros.clasificacion'),
            preserve_default=False,
        ),
    ]
