# Generated by Django 5.2.4 on 2025-07-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_rename_archivo_pdf_libro_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
